### ISSUE TITLE
Add request ID and a couple other headers

### ISSUE THREAD

**Issue by glitch003** [j-labs-xyz/lit-swift-sdk#1]
Hi, this is Chris from Lit Protocol.  This looks great so far!  

We recently changed the headers we send with every request in the JS SDK, can you update the iOS SDK to match?

Here's the code I'm talking about in the JS SDK, for reference: https://github.com/LIT-Protocol/lit-js-sdk/blob/serrano/src/utils/litNodeClient.js#L1955

The headers are: 
* "X-Lit-SDK-Version" - you already have this header so this would just be a rename from what you're using for the version header now
* "X-Lit-SDK-Type" - you can hardcode this to "Swift"
* "X-Request-Id" - This one is the most complex.  Essentially, we are generating a random string for each request prepended with "lit_" and using it to correlate requests across all the nodes, so that nodes can coordinate better.  Note: this needs to be the same request id across all the nodes, per operation.  So you should generate it outside the loop where you loop over the nodes to talk to them, and then pass it in.  You can see how we do this i the JS here: https://github.com/LIT-Protocol/lit-js-sdk/blob/serrano/src/utils/litNodeClient.js#L1658  You're welcome to use whatever random string identifier function you want as long as it's at least 16 bytes, to reduce the possibility of a collision.

Thanks!

**Comment by LevenWin** [comment]
Hi Chris，thanks for your review. I fixed this with https://github.com/j-labs-xyz/lit-swift-sdk/commit/f55a59072214350a8d3d0040fa1da0e2868085fd

**Comment by glitch003** [comment]
Awesome, looks great!  Thanks!
